### ISSUE TITLE
Doesn't work in GNOME Shell 3.20

### ISSUE THREAD

**Issue by BooBerry** [HROMANO/nohotcorner#10]
Exactly that. It doesn't work even after forcing/modifying the extension to install.

**Comment by HROMANO** [comment]
Did you try "master" version ?

**Comment by BooBerry** [comment]
Correct, yes I did. Still didn't work.

**Comment by HROMANO** [comment]
I switched to 3.20 yesterday, and the extension works on both X and Wayland sessions without warnings or errors. Maybe something in your config (other extensions, multi-monitor?).
If you don't have more information, I'll close the report.

**Comment by BooBerry** [comment]
It's working now after a clean install. Thanks!
