### ISSUE TITLE
Does not work for GNOME Shell 3.20

### ISSUE THREAD

**Issue by rob9** [HROMANO/nohotcorner#11]
I installed metadata.js and extension.js to a folder in .local/share/gnome-shell/extensions/

BUG
hot corner is still active
does not appear in GNOME Tweaks / Extensions

using extension.js from previous version: no improvement
- problem likely in metadata.json

using the entire 3.18 version for 3.20, updating metadata.json to include 3.20: WORKS

**Comment by HROMANO** [comment]
3.20 is in metadata.json since October 2015. Don't know what has to be updated. Closing.
