### ISSUE TITLE
GNOME 3.36

### ISSUE THREAD

**Issue by gmejzej** [HROMANO/nohotcorner#16]
Are there plans to release a version that works with GNOME 3.36?

If not, can anyone recommend a good substitute I can use to disable the top left hot corner?

**Comment by HROMANO** [comment]
Hi,
This extension is not needed anymore as it is now supported by the shell itself. You can switch off the hotcorner with a gsettings or using gnome-tweak tool.
Have a nice day.


Le 19 mars 2020 17:42:30 GMT+01:00, gmejzej <notifications@github.com> a écrit :
>Are there plans to release a version that works with GNOME 3.36?
>
>If not, can anyone recommend a good substitute I can use to disable the
>top left hot corner?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/HROMANO/nohotcorner/issues/16

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gmejzej** [comment]
> Hi, This extension is not needed anymore as it is now supported by the shell itself. You can switch off the hotcorner with a gsettings or using gnome-tweak tool. Have a nice day. Le 19 mars 2020 17:42:30 GMT+01:00, gmejzej <notifications@github.com> a écrit :
> […](#)
> Are there plans to release a version that works with GNOME 3.36? If not, can anyone recommend a good substitute I can use to disable the top left hot corner? -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #16
> -- Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

Hi. Thanks for the response. Do you happen to know what the gsetting is?
